# Generated by Django 5.2.7 on 2025-11-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id of an organization')),
                ('ico', models.TextField(verbose_name='ICO (indetifikacne cislo organizacie) of an organization')),
                ('dic', models.TextField(verbose_name='DIC (danove identifikacne cislo) of an organization')),
                ('ic_dph', models.TextField(verbose_name="organization's identificator for taxes")),
                ('name', models.TextField(verbose_name='organization name')),
                ('building_number', models.TextField(verbose_name='building number of an organization')),
                ('country', models.TextField(verbose_name='country, where an organization is located')),
                ('municipality', models.TextField(verbose_name='town, where an organization is located')),
                ('postal_code', models.TextField(verbose_name="organization's local postal code")),
                ('street_name', models.TextField(verbose_name="organization's location street name")),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'organization',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id of a transaction')),
                ('issue_date', models.DateTimeField(verbose_name="transaction's date and time of creating")),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.organization')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'transaction',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name="item's id")),
                ('quantity', models.FloatField(verbose_name='item quantity')),
                ('name', models.TextField(verbose_name="item's name")),
                ('price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='total price of an item')),
                ('ai_name_without_brand_and_quantity', models.TextField(verbose_name='name without brand and quantity')),
                ('ai_name_in_english_without_brand_and_quantity', models.TextField(verbose_name='name in english without brand and quantity')),
                ('ai_brand', models.TextField(verbose_name='brand of an item')),
                ('ai_category', models.TextField(verbose_name='category of an item')),
                ('ai_quantity_value', models.FloatField(verbose_name='quantity value')),
                ('ai_quantity_unit', models.TextField(verbose_name='quantity unit')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.transaction')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'db_table': 'item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id of an unit')),
                ('name', models.TextField(verbose_name='local street name of unit')),
                ('country', models.TextField(verbose_name='country of unit')),
                ('municipality', models.TextField(verbose_name="unit's name of town")),
                ('postal_code', models.TextField(verbose_name="unit's local postal code")),
                ('building_number', models.TextField(verbose_name='building number of unit')),
                ('property_registration_number', models.TextField(verbose_name="unit's property registration number")),
                ('street_name', models.TextField(verbose_name="unit's local street name")),
                ('latitude', models.FloatField(verbose_name="unit's latitude on world map")),
                ('longitude', models.FloatField(verbose_name="unit's longitude on world map")),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.organization')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
                'db_table': 'unit',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.unit'),
        ),
    ]
